export type Product = {
  id: string;
  name: string;
  slug: string;
  description: string;
  sku: string;
  price: number;
  discount_percent: number;
  category: string;
  catalog_group: string;
  catalog_name: string;
  brand: string;
  options: Record<string, string>;
  tags: string[];
  specifications: { label: string; value: string }[];
  source_url: string;
  stock: number;
  reserved: number;
  available: number;
  kind: 'store' | 'preorder';
  status: 'draft' | 'published' | 'withdrawn';
  images: string[];
  opens_at: string | null;
  closes_at: string | null;
  max_per_customer: number | null;
  delivery_terms: string;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
  version: number;
};
export type User = {
  id: string;
  email: string;
  name: string;
  role: 'admin' | 'customer';
  email_verified: boolean;
  phone: string;
  konami_id: string;
  klu_code: string;
  address: Record<string, string>;
  created_at: string;
};
export type Post = {
  id: string;
  slug: string;
  kind: 'news' | 'community' | 'tournament';
  title: string;
  body: string;
  image: string;
  event_at: string | null;
  event_level?: 'normal' | 'featured' | 'major';
  entry_price?: number | null;
  repeat_weekly?: boolean;
  repeat_until?: string | null;
  excluded_dates?: string[];
  exception_parent_id?: string | null;
  exception_day?: string | null;
  series_id?: string;
  location: string;
  status: 'draft' | 'published' | 'withdrawn';
  created_at: string;
  updated_at: string;
};
export type Carrier = {
  id: string;
  name: string;
  enabled: boolean;
  mode: 'address' | 'agency';
  collect: boolean;
  price: number;
};
export type TwitchVideo = {
  id: string;
  video_id: string;
  channel: string;
  title: string;
  recorded_at: string;
  twitch_thumbnail: string;
  custom_thumbnail: string;
  tournament_id: string | null;
  status?: 'draft' | 'published' | 'withdrawn';
};
export type YouTubeVideo = {
  id: string;
  video_id: string;
  title: string;
  recorded_at: string;
  youtube_thumbnail: string;
  custom_thumbnail: string;
  tournament_id: string | null;
  status?: 'draft' | 'published' | 'withdrawn';
};
export type TournamentMedia = {
  provider: 'youtube';
  channel_url: string;
  live: {
    enabled: boolean;
    video_id: string;
    title: string;
    stage: 'scheduled' | 'live';
    tournament_id: string | null;
  } | null;
  videos: YouTubeVideo[];
  total: number;
};
export type Settings = {
  payment_mode?: 'disabled' | 'sandbox' | 'production';
  name: string;
  description: string;
  address: string;
  hours: string;
  pickup_instructions: string;
  phone: string;
  email: string;
  reservation_minutes: number;
  carriers: Carrier[];
};
export type OrderItem = {
  product_id: string;
  name: string;
  sku: string;
  quantity: number;
  unit_price: number;
  original_price: number;
  kind: string;
  image: string;
};
export type Order = {
  id: string;
  number: number;
  user_id: string | null;
  customer_email: string;
  customer_name: string;
  source: 'web' | 'pos';
  payment_environment: 'sandbox' | 'production' | null;
  can_refresh_payment: boolean;
  can_manage_delivery: boolean;
  payment_status: 'pending' | 'approved' | 'rejected' | 'expired' | 'review';
  fulfillment_status: 'received' | 'preparing' | 'ready' | 'shipped' | 'delivered' | 'cancelled';
  subtotal: number;
  shipping_price: number;
  total: number;
  delivery: Record<string, string | number | boolean>;
  items: OrderItem[];
  payment_method: string;
  cash_received: number | null;
  change_amount: number | null;
  carrier: string;
  tracking: string;
  expires_at: string | null;
  reservation_released_at: string | null;
  created_at: string;
  updated_at: string;
  events?: { id: string; message: string; created_at: string }[];
  payment_url?: string;
};
export type CartItem = { product_id: string; quantity: number };
export type Dashboard = {
  products: number;
  orders: number;
  pending: number;
  low_stock: number;
  revenue: number;
  recent_orders: Order[];
};
